name: fl_apirest
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  splash_screen_view: ^3.0.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/
  - assets/images/Move_Images/Akuma/
  - assets/images/Move_Images/Amingo/
  - assets/images/Move_Images/Anakaris/
  - assets/images/Move_Images/Baby Bonnie Hood/
  - assets/images/Move_Images/Blackheart/
  - assets/images/Move_Images/Cable/
  - assets/images/Move_Images/Cammy/
  - assets/images/Move_Images/Captain America/
  - assets/images/Move_Images/Captain Commando/
  - assets/images/Move_Images/Charlie/
  - assets/images/Move_Images/Chun-Li/
  - assets/images/Move_Images/Colossus/
  - assets/images/Move_Images/Cyclops/
  - assets/images/Move_Images/Dan/
  - assets/images/Move_Images/Dhalsim/
  - assets/images/Move_Images/Doctor Doom/
  - assets/images/Move_Images/Felicia/
  - assets/images/Move_Images/Gambit/
  - assets/images/Move_Images/Guile/
  - assets/images/Move_Images/Hayato/
  - assets/images/Move_Images/Hulk/
  - assets/images/Move_Images/Ice Man/
  - assets/images/Move_Images/Iron Man/
  - assets/images/Move_Images/Jill/
  - assets/images/Move_Images/Jin/
  - assets/images/Move_Images/Juggernaut/
  - assets/images/Move_Images/Ken/
  - assets/images/Move_Images/Magneto/
  - assets/images/Move_Images/Marrow/
  - assets/images/Move_Images/Mega Man/
  - assets/images/Move_Images/Morrigan/
  - assets/images/Move_Images/Omega Red/
  - assets/images/Move_Images/Psylocke/
  - assets/images/Move_Images/Rogue/
  - assets/images/Move_Images/Roll/
  - assets/images/Move_Images/Ruby Heart/
  - assets/images/Move_Images/Ryu/
  - assets/images/Move_Images/Sabretooth/
  - assets/images/Move_Images/Sakura/
  - assets/images/Move_Images/Sakura (Dark)/
  - assets/images/Move_Images/Sentinel/
  - assets/images/Move_Images/Servbot/
  - assets/images/Move_Images/Shuma-Gorath/
  - assets/images/Move_Images/Silver Samurai/
  - assets/images/Move_Images/SonSon/
  - assets/images/Move_Images/Spider-Man/
  - assets/images/Move_Images/Spiral/
  - assets/images/Move_Images/Storm/
  - assets/images/Move_Images/Strider/
  - assets/images/Move_Images/Thanos/
  - assets/images/Move_Images/Tron Bonne/
  - assets/images/Move_Images/Vega/
  - assets/images/Move_Images/Venom/
  - assets/images/Move_Images/War Machine/
  - assets/images/Move_Images/Wolverine/
  - assets/images/Move_Images/Wolverine, Bone/
  - assets/images/Move_Images/Zangief/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
