// Generated by https://quicktype.io
class MovesModel {
  String? characterName;
  String? moveName;
  String? image;

  MovesModel({
    this.characterName,
    this.moveName,
    this.image,
  });

  factory MovesModel.fromMap(Map<String, dynamic>map){
    return MovesModel(
      characterName: map['character_name'],
      moveName: map['move_name'],
      image:map['image']
    );
  }
}
