// Generated by https://quicktype.io

class PersonajesModel {
  String? name;
  String? headShot;
  String? universe;

  PersonajesModel({
    this.name,
    this.headShot,
    this.universe,
  });

  factory PersonajesModel.fromMap(Map<String, dynamic> map){
    return PersonajesModel(
      name: map['name'],
      headShot: map['head_shot'] ?? '',
      universe: map['universe']
    );
  }
}
